INSERT INTO public.aircrafts (aircraft_model) VALUES ('Airbus A300 medium-range widebody airliner');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Airbus A310 widebody airliner');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Airbus A318 100-seat airliner');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Airbus A319 airliner and large corporate jet');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Airbus A320 airliner');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Airbus A321 narrowbody airliner');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Airbus A330 widebody airliner');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Airbus A340 widebody airliner');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Airbus A350 widebody airliner');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Airbus A380 high-capacity widebody airliner');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Airbus Beluga high-capacity transport aircraft');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Boeing Model 221 air mail carrier');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Boeing 247 propeller airliner');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Boeing 307 Stratoliner propeller airliner');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Boeing 707 medium/long-range airliner and freighter');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Boeing 717 short- to medium-range airliner');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Boeing 720 medium-range narrowbody airliner');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Boeing 727 short- to medium-range narrowbody airliner');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Boeing 737 short- to medium-range narrowbody airliner');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Boeing 747 long-range high-capacity widebody airliner');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Boeing 757 Medium-range to long-range narrowbody airliner');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Bombardier Dash Q-400 Turboprop airliner');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Breguet 890 Mercure twin-engine transport');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Cessna 182 four-seat light aircraft');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Cessna 750 Citation X long-range corporate jet');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Dassault Falcon 50 long-range midsize corporate jet');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Douglas DC-9 jet airliner');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Douglas DC-10 widebody tri-jet airliner');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Embraer 170 70-seat medium-range jet airliner');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Fokker 100 100-seat regional jet');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Piper PA-44 Seminole four-seat light twin');
INSERT INTO public.aircrafts (aircraft_model) VALUES ('Rockwell Sabreliner corporate jet');


INSERT INTO public.crew_members (first_name, last_name, birth_date) VALUES ('Jean', 'Mermoz', '1901-12-09');
INSERT INTO public.crew_members (first_name, last_name, birth_date) VALUES ('Calbraith', 'Rogers', '1879-01-12');
INSERT INTO public.crew_members (first_name, last_name, birth_date) VALUES ('Noel', 'Wien', '1899-06-08');
INSERT INTO public.crew_members (first_name, last_name, birth_date) VALUES ('Buzz', 'Aldrin', '1930-01-12');
INSERT INTO public.crew_members (first_name, last_name, birth_date) VALUES ('Pancho', 'Barnes', '1901-07-22');
INSERT INTO public.crew_members (first_name, last_name, birth_date) VALUES ('Amelia', 'Earhart', '1950-07-24');
INSERT INTO public.crew_members (first_name, last_name, birth_date) VALUES ('Bob', 'Hoover', '1922-01-24');
INSERT INTO public.crew_members (first_name, last_name, birth_date) VALUES ('Charles', 'Lindbergh', '1902-02-04');
INSERT INTO public.crew_members (first_name, last_name, birth_date) VALUES ('Bessie', 'Coleman', '1892-01-26');
INSERT INTO public.crew_members (first_name, last_name, birth_date) VALUES ('Antoine', 'de Saint-Exupery', '1900-06-29');
INSERT INTO public.crew_members (first_name, last_name, birth_date) VALUES ('John', 'Denver', '1943-12-31');
INSERT INTO public.crew_members (first_name, last_name, birth_date) VALUES ('George W.', 'Bush', '1946-07-06');


INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (1, 5);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (1, 8);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (1, 9);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (1, 11);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (4, 1);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (4, 3);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (4, 9);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (8, 2);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (8, 4);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (8, 5);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (8, 9);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (8, 12);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (9, 1);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (9, 4);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (9, 1);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (9, 9);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (9, 10);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (9, 12);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (10, 1);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (10, 2);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (10, 5);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (10, 7);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (14, 2);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (14, 7);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (19, 4);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (19, 9);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (19, 12);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (20, 1);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (20, 5);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (20, 8);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (20, 11);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (24, 1);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (24, 2);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (24, 3);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (24, 5);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (24, 7);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (24, 8);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (24, 10);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (26, 3);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (27, 1);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (27, 3);
INSERT INTO public.aircraft_crew_member (aircraft_id, crew_member_id) VALUES (30, 4);
